### ISSUE TITLE
Having some issues attempting to export.

### ISSUE THREAD

**Issue by GlitchRobin** [xyrin88/anthemtool#2]
![e90d36c83fc9346f8835b65570cd0d9a](https://user-images.githubusercontent.com/29992274/70842936-1c2c9480-1df8-11ea-82b4-68b511d3309b.png)
It does this after listing a bunch of stuff as unavailable/ignoring some unexpected bytes.
![70d767c0f0a6ccf08bfe026c7187f526](https://user-images.githubusercontent.com/29992274/70842948-41210780-1df8-11ea-8a3e-2f77898de561.png)

**Comment by GlitchRobin** [comment]
I currently have Python 3.8 64bit installed

**Comment by 0xDeve** [comment]
Same issues, do you have a fix for this?

**Comment by GlitchRobin** [comment]
Stale thread, its been 4 years. Unfortunately don't know of any fixes
